#!/usr/bin/env python3
"""Generate src/sprites_data.ts from scorch.sprites by REFLECTION.

The embedded byte-art tables in scorch/sprites.py (sprite Table A/B, the 7 tank
stroke lists + their turret/word0 metadata, the proportional font, the cursor,
the window icon, the shop-icon RGB6 band, the title-mountain whitelist, and the
inspection palette) are the load-bearing RE artifacts.  Rather than hand-
transcribe them into TypeScript (error-prone, and the cause of two prior aborted
attempts), this script imports the real module and emits each table as an exact
TS literal.  Byte-for-byte identical by construction.

Run (from scorch-html5/):
  SDL_VIDEODRIVER=dummy PYTHONPATH="/abs/scorch-py" /abs/.venv/bin/python \
      oracle/gen_sprites_data.py
"""
import os
import sys

os.environ.setdefault("SDL_VIDEODRIVER", "dummy")

from scorch import sprites  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "sprites_data.ts")


def u8_array(name, raw):
    """`export const NAME = new Uint8Array([..]);` from a bytes object."""
    body = ", ".join(str(b) for b in raw)
    return f"export const {name} = new Uint8Array([{body}]);\n"


def u8_array_of_arrays(name, list_of_bytes):
    """`export const NAME: Uint8Array[] = [ new Uint8Array([..]), .. ];`."""
    lines = [f"export const {name}: Uint8Array[] = ["]
    for rec in list_of_bytes:
        body = ", ".join(str(b) for b in rec)
        lines.append(f"  new Uint8Array([{body}]),")
    lines.append("];\n")
    return "\n".join(lines)


def number_triples(name, triples):
    """`export const NAME: ReadonlyArray<[number,number,number]> = [[..],..];`."""
    items = ", ".join(f"[{a}, {b}, {c}]" for (a, b, c) in triples)
    return (
        f"export const {name}: ReadonlyArray<readonly [number, number, number]> "
        f"= [{items}];\n"
    )


def number_pairs(name, pairs):
    items = ", ".join(f"[{a}, {b}]" for (a, b) in pairs)
    return (
        f"export const {name}: ReadonlyArray<readonly [number, number]> "
        f"= [{items}];\n"
    )


def num_map_triples(name, d):
    """A {index: (dx,dy,c)...} keyed map -> a record of triples, keyed by int."""
    lines = [
        f"export const {name}: {{ readonly [k: number]: "
        f"ReadonlyArray<readonly [number, number, number]> }} = {{"
    ]
    for k in sorted(d):
        items = ", ".join(f"[{a}, {b}, {c}]" for (a, b, c) in d[k])
        lines.append(f"  {k}: [{items}],")
    lines.append("};\n")
    return "\n".join(lines)


def num_map_pair(name, d):
    lines = [
        f"export const {name}: {{ readonly [k: number]: "
        f"readonly [number, number] }} = {{"
    ]
    for k in sorted(d):
        a, b = d[k]
        lines.append(f"  {k}: [{a}, {b}],")
    lines.append("};\n")
    return "\n".join(lines)


def num_map_scalar(name, d):
    lines = [f"export const {name}: {{ readonly [k: number]: number }} = {{"]
    for k in sorted(d):
        lines.append(f"  {k}: {d[k]},")
    lines.append("};\n")
    return "\n".join(lines)


def rgb_map(name, d):
    """{idx: (r,g,b)} -> record of triples (the inspection palette)."""
    lines = [
        f"export const {name}: {{ readonly [k: number]: "
        f"readonly [number, number, number] }} = {{"
    ]
    for k in sorted(d):
        r, g, b = d[k]
        lines.append(f"  {k}: [{r}, {g}, {b}],")
    lines.append("};\n")
    return "\n".join(lines)


def rgb_list(name, lst):
    items = ", ".join(f"[{r}, {g}, {b}]" for (r, g, b) in lst)
    return (
        f"export const {name}: ReadonlyArray<readonly [number, number, number]> "
        f"= [{items}];\n"
    )


def hex_map(name, d):
    """{code: "hexstring"} -> a record of Uint8Array (the font glyphs)."""
    lines = [
        f"export const {name}: {{ readonly [code: number]: Uint8Array }} = {{"
    ]
    for k in sorted(d):
        raw = bytes.fromhex(d[k])
        body = ", ".join(str(b) for b in raw)
        lines.append(f"  {k}: new Uint8Array([{body}]),")
    lines.append("};\n")
    return "\n".join(lines)


def str_tuple(name, t):
    items = ", ".join(f'"{s}"' for s in t)
    return f"export const {name}: readonly string[] = [{items}];\n"


def main():
    parts = []
    parts.append(
        "/* AUTO-GENERATED by oracle/gen_sprites_data.py from scorch.sprites.\n"
        " * Do NOT edit by hand.  Every table here is reflected byte-for-byte from\n"
        " * the Python oracle (which itself is byte-verified against SCORCH.EXE).\n"
        " * Regenerate with:\n"
        " *   SDL_VIDEODRIVER=dummy PYTHONPATH=.../scorch-py .../python "
        "oracle/gen_sprites_data.py\n"
        " */\n"
    )

    # 1. Sprite Tables A (48 recs) and B (12 recs): raw byte records.
    parts.append(u8_array_of_arrays("TABLE_A_RAW", sprites._TABLE_A_RAW))
    parts.append(u8_array_of_arrays("TABLE_B_RAW", sprites._TABLE_B_RAW))

    # 2. Inspection palette (_VIS_RGB) and shop-icon RGB6 band + WEAPON_ICON_BASE.
    parts.append(rgb_map("VIS_RGB", sprites._VIS_RGB))
    parts.append(rgb_list("SHOP_ICON_RGB6", sprites._SHOP_ICON_RGB6))
    parts.append(f"export const WEAPON_ICON_BASE = {sprites.WEAPON_ICON_BASE};\n")

    # 3. Tank designs: 7 stroke lists (dx,dy,c), turret mounts, word0/barrel len.
    parts.append(num_map_triples("TANK_STROKES", sprites._TANK_STROKES))
    parts.append(num_map_pair("TANK_TURRET", sprites._TANK_TURRET))
    parts.append(num_map_scalar("TANK_WORD0", sprites._TANK_WORD0))
    parts.append(f"export const NUM_TANK_DESIGNS = {sprites.NUM_TANK_DESIGNS};\n")
    parts.append(f"export const BARREL_LEN_DEFAULT = {sprites._BARREL_LEN};\n")

    # 4. Proportional bitmap font (161 glyphs) + the fixed 12-row cell height.
    parts.append(hex_map("FONT_GLYPH_BYTES", sprites._FONT_GLYPH_HEX))
    parts.append(f"export const FONT_ROWS = {sprites._FONT_ROWS};\n")

    # 5. Mouse cursor: hotspot + 28 (dx,dy) points.
    parts.append(
        f"export const CURSOR_HOTSPOT: readonly [number, number] = "
        f"[{sprites.CURSOR_HOTSPOT[0]}, {sprites.CURSOR_HOTSPOT[1]}];\n"
    )
    parts.append(number_pairs("CURSOR_POINTS", sprites.CURSOR_POINTS))

    # 6. Window icon: dims, 16-color palette, packed 4-bpp XOR + 1-bpp AND mask.
    parts.append(f"export const ICON_W = {sprites._ICON_W};\n")
    parts.append(f"export const ICON_H = {sprites._ICON_H};\n")
    parts.append(rgb_list("ICON_PALETTE", sprites._ICON_PALETTE))
    parts.append(u8_array("ICON_XOR", bytes.fromhex(sprites._ICON_XOR_HEX)))
    parts.append(u8_array("ICON_AND", bytes.fromhex(sprites._ICON_AND_HEX)))

    # 7. Title-mountain default + whitelist.
    parts.append(
        f'export const TITLE_MTN_DEFAULT = "{sprites.TITLE_MTN_DEFAULT}";\n'
    )
    parts.append(str_tuple("TITLE_MTN_WHITELIST", sprites.TITLE_MTN_WHITELIST))

    with open(OUT, "w") as fh:
        fh.write("\n".join(parts))
    # Report sizes so a regression in the reflection is visible.
    print("wrote", os.path.abspath(OUT))
    print("  TABLE_A_RAW recs:", len(sprites._TABLE_A_RAW))
    print("  TABLE_B_RAW recs:", len(sprites._TABLE_B_RAW))
    print("  tank designs:", len(sprites._TANK_STROKES))
    print("  font glyphs:", len(sprites._FONT_GLYPH_HEX))
    print("  cursor points:", len(sprites.CURSOR_POINTS))
    print("  icon xor bytes:", len(bytes.fromhex(sprites._ICON_XOR_HEX)))
    print("  whitelist:", len(sprites.TITLE_MTN_WHITELIST))


if __name__ == "__main__":
    sys.exit(main())
