/**
 * Original Scorched Earth v1.5 sprites -- REAL artwork extracted from the binary.
 *
 * Faithful TypeScript port of scorch-py/scorch/sprites.py (the fidelity oracle,
 * itself decoded byte-for-byte from 1.5/SCORCH.EXE).  The embedded byte-art tables
 * live in ./sprites_data (generated by oracle/gen_sprites_data.py reflecting the
 * Python module, so they are byte-identical by construction); this file carries the
 * LOGIC: record decode, sprite Surface build, the per-design vector-stroke tank
 * body + Bresenham barrel, the Tank-Initialization appearance cell, the shop weapon-
 * icon palette band, the proportional font, the cursor, the window icon, and the
 * title .MTN -> Surface decode.  The FUN_/DAT_ provenance from the Python source is
 * preserved verbatim so the lineage survives.
 *
 * Provenance (all FACT, decoded from 1.5/SCORCH.EXE; carried from sprites.py):
 *   * TWO embedded sprite tables, decoded by the blitter FUN_2f71_0000 (icons.cpp,
 *     seg 2f71).  Table A: base 5f38:0x3826, 48 records (weapon/HUD/UI icons);
 *     Table B: base 5f38:0x324a, 12 records (cursors, parachute, tank, bomb, dome,
 *     crate).  Data-seg file offset = 0x55d80 + seg_offset.
 *   * Record format (FUN_2f71_00c7/_0135/_01a3 for A, FUN_2f71_0210/_0280 for B):
 *       byte0 = xoff (signed char), byte1 = yoff (signed char), byte2 = width,
 *       byte3.. = SIGNED palette-index pixels, row advances every `width` pixels,
 *       until terminator 0x9D (-99).  Stride 0x7d = 125 bytes.
 *   * Blit modes (FUN_2f71_0000.c:17-41): pixel 0 is transparent; the tank/weapon
 *     icons use the REMAP path abs(pixel)+color (palette tint).
 *   * The in-PLAY tank BODY is per-design VECTOR-STROKE art (FUN_4912_0007 ->
 *     FUN_49d4_0335 -> FUN_49d4_04d9).  SEVEN designs, each a list of (dx,dy,shade)
 *     triples; recovered byte-exact in sprites_data.TANK_STROKES.  The barrel
 *     (FUN_4912_021f) is a line from the per-design turret mount at the aim angle.
 *
 * PALETTE NOTE: the sprite pixel bytes are palette INDICES.  For standalone
 * rendering this module maps the small indices the sprites use to a legible
 * inspection RGB (VIS_RGB).  With a real palette + `color` remap base, bitmaps tint
 * through the recovered index bands exactly as the original does (abs(idx)+color).
 *
 * DOM SAFETY: the pixel-decode core is DOM-free (it emits column-major RGB/alpha
 * Uint8Arrays, the surfarray contract from src/pygame.ts).  Surfaces are built only
 * inside the Surface-returning functions (get_sprite/draw_tank/...), so the module
 * imports safely under Node (the differential test drives the pure core, which needs
 * no canvas).
 *
 * surfarray CONTRACT (matches the numpy oracle byte-for-byte, src/pygame.ts):
 *   RGB buffer is COLUMN-MAJOR  rgb[(x*h + y)*3 + c], length w*h*3.
 *   alpha plane is COLUMN-MAJOR alpha[x*h + y], length w*h.
 * (numpy's array3d(surf) is (w,h,3); its C-order flatten IS (x*h+y)*3+c.  This was
 * pinned empirically against headless pygame: set_at((3,1)) -> flat index 3*h+1.)
 */

import * as pygame from "./pygame";
import * as _pal from "./palette";
import { build_palette } from "./palette";
import { parseHeader as mtnParseHeader, decode as mtnDecode } from "./mtn";
import type { Rgb as MtnRgb } from "./mtn";
import * as data from "./sprites_data";

// Re-export the band base the shop/HUD index weapon icons through (sprites.py:279).
export const WEAPON_ICON_BASE = data.WEAPON_ICON_BASE; // 0xAA

type RGB = [number, number, number];

// --------------------------------------------------------------------------
// Record decode  (FUN_2f71_0000 walk).
// --------------------------------------------------------------------------

/** signed-char of a byte: b - 256 if b >= 128 (sprites.py _s8). */
function s8(b: number): number {
  return b >= 128 ? b - 256 : b;
}

export interface DecodedRecord {
  xoff: number;
  yoff: number;
  width: number;
  height: number;
  /** flat row-major signed palette indices, length width*height (0-padded tail). */
  pixels: number[];
}

/**
 * Decode one raw sprite record into (xoff, yoff, width, height, pixels).
 *
 * `pixels` is a flat list of SIGNED palette indices, row-major, length
 * width*height (last partial row right-padded with 0).  Faithful to FUN_2f71_0000:
 * read bytes until 0x9D, advancing a row every `width` pixels.  (sprites.py
 * decode_record.)
 */
export function decodeRecord(rec: Uint8Array): DecodedRecord {
  const xoff = s8(rec[0]);
  const yoff = s8(rec[1]);
  const width = rec[2];
  const px: number[] = [];
  let i = 3;
  while (i < rec.length && rec[i] !== 0x9d) {
    px.push(s8(rec[i]));
    i += 1;
  }
  const height = width ? Math.floor((px.length + width - 1) / width) : 0;
  while (px.length < width * height) px.push(0);
  return { xoff, yoff, width, height, pixels: px };
}

function rawRecord(table: string, index: number): Uint8Array {
  return (table === "A" ? data.TABLE_A_RAW : data.TABLE_B_RAW)[index];
}

/**
 * Narrow a public `pal` option to a PaletteTable.  The two SpritesProvider shapes
 * type `pal` differently -- render.ts as `_pal.PaletteTable`, screens.ts as
 * `unknown` -- so the public functions accept `unknown` (the only type assignable
 * FROM both) and narrow here.  A non-array (or undefined) `pal` means "no remap",
 * which falls back to the inspection palette (sprites.py's color/pal both-None path).
 */
function asPalette(pal: unknown): _pal.PaletteTable | undefined {
  return Array.isArray(pal) ? (pal as _pal.PaletteTable) : undefined;
}

// --------------------------------------------------------------------------
// Index -> RGB  (the remap / inspection split, sprites.py _index_to_rgb).
// --------------------------------------------------------------------------

/**
 * Map a (positive, abs-taken) palette index to RGB.
 *
 * If `color` is given and a real palette `pal` (256x3) is available, follow the
 * original remap: plot index (abs(idx)+color) through the palette.  Otherwise fall
 * back to the legible inspection palette VIS_RGB (magenta for an unknown index,
 * matching sprites.py's (255,0,255) default).
 */
function indexToRgb(idx: number, color?: number, pal?: _pal.PaletteTable): RGB {
  const a = Math.abs(idx);
  if (color !== undefined && color !== null && pal !== undefined && pal !== null) {
    const j = Math.max(0, Math.min(255, a + color));
    const row = pal[j];
    return [row[0] | 0, row[1] | 0, row[2] | 0];
  }
  const v = data.VIS_RGB[a];
  return v !== undefined ? [v[0], v[1], v[2]] : [255, 0, 255];
}

// --------------------------------------------------------------------------
// Pure pixel buffers (DOM-free; the differential test asserts these).
// --------------------------------------------------------------------------

/** A decoded sprite's pixels in the surfarray COLUMN-MAJOR contract. */
export interface PixelBuffer {
  w: number;
  h: number;
  /** column-major RGB: rgb[(x*h + y)*3 + c], length w*h*3 (0 where transparent). */
  rgb: Uint8Array;
  /** column-major alpha: alpha[x*h + y], length w*h (0 transparent, 255 opaque). */
  alpha: Uint8Array;
}

/** Allocate a transparent (RGB=0, alpha=0) column-major buffer of size w*h. */
function blankBuffer(w: number, h: number): PixelBuffer {
  const ww = Math.max(1, w);
  const hh = Math.max(1, h);
  return {
    w: ww,
    h: hh,
    rgb: new Uint8Array(ww * hh * 3),
    alpha: new Uint8Array(ww * hh),
  };
}

/** Plot one scaled block at source pixel (rx, ry) -- mirrors the scale==1 set_at
 *  vs scale>1 fill in sprites.py _build_surface.  Coordinates are surface pixels. */
function plotBlock(
  buf: PixelBuffer,
  sx: number,
  sy: number,
  scale: number,
  rgb: RGB,
): void {
  for (let yy = 0; yy < scale; yy++) {
    const py = sy + yy;
    if (py < 0 || py >= buf.h) continue;
    for (let xx = 0; xx < scale; xx++) {
      const px = sx + xx;
      if (px < 0 || px >= buf.w) continue;
      const ai = px * buf.h + py;
      const ri = ai * 3;
      buf.rgb[ri] = rgb[0];
      buf.rgb[ri + 1] = rgb[1];
      buf.rgb[ri + 2] = rgb[2];
      buf.alpha[ai] = 255;
    }
  }
}

/**
 * Build a sprite record's pixels into a column-major PixelBuffer.
 *
 * Mirrors sprites.py _build_surface: a (w*scale, h*scale) SRCALPHA surface filled
 * transparent, then every NONZERO source pixel plotted opaque (a single set_at at
 * scale 1, a scale x scale block otherwise).  pixel 0 stays transparent.
 */
export function buildSpritePixels(
  rec: Uint8Array,
  opts: { color?: number; pal?: _pal.PaletteTable; scale?: number } = {},
): PixelBuffer {
  const scale = opts.scale ?? 1;
  const { width: w, height: h, pixels } = decodeRecord(rec);
  const buf = blankBuffer(w * scale, h * scale);
  for (let ry = 0; ry < h; ry++) {
    for (let rx = 0; rx < w; rx++) {
      const v = pixels[ry * w + rx];
      if (v === 0) continue; // transparent
      const rgb = indexToRgb(v, opts.color, opts.pal);
      plotBlock(buf, rx * scale, ry * scale, scale, rgb);
    }
  }
  return buf;
}

/** Build a Surface from a column-major PixelBuffer (RGB via blit_array, then the
 *  alpha plane), matching the load_title_mountain pattern in src/pygame.ts. */
function surfaceFromBuffer(buf: PixelBuffer): pygame.Surface {
  // READBACK: pixels_alpha below reads the surface right back (getImageData).
  const surf = new pygame.Surface([buf.w, buf.h], pygame.SRCALPHA | pygame.READBACK);
  surf.fill([0, 0, 0, 0]);
  pygame.surfarray.blit_array(surf, { w: buf.w, h: buf.h, data: buf.rgb });
  pygame.surfarray.pixels_alpha(surf).set(buf.alpha);
  return surf;
}

// --------------------------------------------------------------------------
// get_sprite / table getters  (the SpritesProvider get_sprite).
// --------------------------------------------------------------------------

/**
 * Return a pygame Surface for one real sprite record.
 *
 * table: "A" (48 weapon/HUD icons) or "B" (12 cursor/parachute/tank/bomb).
 * color: remap base; with `pal` (256x3) supplied, pixels plot as abs+color.
 * (sprites.py get_sprite.)  Out-of-range index throws like the Python list index.
 */
export function get_sprite(
  table: string,
  index: number,
  opts: { color?: number; pal?: unknown; scale?: number } = {},
): pygame.Surface | null {
  const rec = rawRecord(table, index);
  if (rec === undefined) return null;
  return surfaceFromBuffer(
    buildSpritePixels(rec, {
      color: opts.color,
      pal: asPalette(opts.pal),
      scale: opts.scale,
    }),
  );
}

/** All 48 real Table-A sprites (weapon/HUD/UI icons) as Surfaces. */
export function get_table_a(opts: {
  color?: number;
  pal?: _pal.PaletteTable;
  scale?: number;
} = {}): pygame.Surface[] {
  return data.TABLE_A_RAW.map((rec) => surfaceFromBuffer(buildSpritePixels(rec, opts)));
}

/** All 12 real Table-B sprites (cursors, parachute, tank, bomb, ...). */
export function get_table_b(opts: {
  color?: number;
  pal?: _pal.PaletteTable;
  scale?: number;
} = {}): pygame.Surface[] {
  return data.TABLE_B_RAW.map((rec) => surfaceFromBuffer(buildSpritePixels(rec, opts)));
}

// --------------------------------------------------------------------------
// Weapon-icon palette band  (sprites.py weapon_icon_palette).
// --------------------------------------------------------------------------

let _weaponIconPalCache: _pal.PaletteTable | null = null;

/**
 * 256x3 palette: the in-game base with the weapon-icon band (0xAA..0xBE) overlaid,
 * so any weapon's real Table-A icon renders in its authored colours
 * (FUN_1dbc_1aa8.c:26-47), NOT the VIS_RGB inspection fallback.  The band RGB is
 * SHOP_ICON_RGB6 expanded 6->8 bit (<< 2).  (sprites.py weapon_icon_palette.)
 */
export function weapon_icon_palette(): _pal.PaletteTable {
  if (_weaponIconPalCache === null) {
    const base: _pal.PaletteTable = build_palette(); // already (256,3)
    for (let i = 0; i < data.SHOP_ICON_RGB6.length; i++) {
      const [r, g, b] = data.SHOP_ICON_RGB6[i];
      base[WEAPON_ICON_BASE + i] = [(r << 2) & 0xff, (g << 2) & 0xff, (b << 2) & 0xff];
    }
    _weaponIconPalCache = base;
  }
  return _weaponIconPalCache;
}

// ==========================================================================
// Tank body -- the REAL per-design VECTOR-STROKE art (sprites_data.TANK_STROKES).
//
// FUN_4912_0007 (per-tank draw dispatch) calls: (1) FUN_49d4_0335 -> FUN_49d4_04d9
// = the design stroke list (the silhouette); (2) FUN_4912_021f = the barrel line +
// muzzle dot; (3) FUN_4912_0526 ONLY when tank+0xc != 0 (special hull, not the
// normal tank).  SEVEN designs, keyed by DESIGN INDEX (the pointer table at
// DS:0x6734+idx*0x12 is non-monotonic in file order; sprites_data keys by index).
//
// STROKE: (dx,dy,c).  dx,dy signed pixel offset from the tank origin (dy<=0 = up,
// origin at the wheel/ground row), c = shade index.  X is mirrored by facing
// (FUN_49d4_04d9.c:20 vs 26).  Barrel length = per-design word0 (Target 2:
// FUN_4912_021f radius = tank[+0x2] = ROUND(word0)).
// ==========================================================================

export const NUM_TANK_DESIGNS = data.NUM_TANK_DESIGNS; // 7
export const TANK_ICON_COUNT = NUM_TANK_DESIGNS;
const BARREL_LEN_DEFAULT = data.BARREL_LEN_DEFAULT; // design 0 = 8

/** Clamp an icon/design index to a valid design (sprites.py _design_strokes). */
function designIndex(idx: number): number {
  return idx >= 0 && idx < NUM_TANK_DESIGNS ? idx : 0;
}

/** Per-design barrel length (pixels).  RECOVERED = design word0 (Target 2). */
function barrelLen(idx: number): number {
  const v = data.TANK_WORD0[Math.trunc(idx)];
  return v !== undefined ? v : BARREL_LEN_DEFAULT;
}

/** Whether a design draws the color-7 wheel/tread band (sprites.py tank_design_wheels). */
export function tank_design_wheels(idx: number): boolean {
  if (idx >= 0 && idx < NUM_TANK_DESIGNS) {
    return data.TANK_STROKES[idx].some((p) => p[2] === 7);
  }
  return true;
}

/**
 * Map a stroke SHADE index `c` to an RGB from the team color `col`
 * (sprites.py _shade_rgb).  RECOVERED color math: the per-player 8-entry DAC band
 * is filled by FUN_3014_1a52/_19e5: slot {0,1,2,3,4,6} -> flat team color; slot 5
 * -> (0x3f,0x3f,0x3f) white shield highlight; slot 7 -> (0x1e,0x1e,0x1e) dark grey
 * tread.  6-bit DAC -> 8-bit is << 2: 0x3f -> 252, 0x1e -> 120.  So stroke shades
 * {0,1,2,3} all render as the SAME flat team color; shade 7 is the fixed grey tread.
 */
function shadeRgb(col: RGB, c: number): RGB {
  if (c === 5) return [252, 252, 252]; // 0x3f<<2 white shield highlight
  if (c === 7) return [120, 120, 120]; // 0x1e<<2 dark-grey tread/shadow
  // slots 0,1,2,3,4,6: flat team color.
  return [Math.min(255, col[0] | 0), Math.min(255, col[1] | 0), Math.min(255, col[2] | 0)];
}

/** The barrel pen (sprites.py _barrel_color): FUN_4912_021f.c:50 sets the pen to
 *  the player band's slot 4 = the FLAT team color.  Not white, not lightened. */
function barrelColor(color: RGB): RGB {
  return [Math.min(255, color[0] | 0), Math.min(255, color[1] | 0), Math.min(255, color[2] | 0)];
}

/**
 * Bresenham line (both endpoints inclusive) plotting opaque `rgb` into `buf`.
 *
 * Reproduces pygame.draw.line for width 1 (validated byte-exact vs pygame 2.6.1
 * across every degree 0..180 at the four barrel lengths) and for an AXIS-ALIGNED
 * width>1 line (the scale>=2 barrel is always angle 90 = vertical; pygame thickens
 * such a line by (width-1) cells on the +perpendicular side, matched here).  A
 * width>1 DIAGONAL is not produced by this module and is not reproduced.
 */
function bresenhamLine(
  buf: PixelBuffer,
  x0: number,
  y0: number,
  x1: number,
  y1: number,
  width: number,
  rgb: RGB,
): void {
  const dx = Math.abs(x1 - x0);
  const dy = Math.abs(y1 - y0);
  const sx = x0 < x1 ? 1 : -1;
  const sy = y0 < y1 ? 1 : -1;
  // Thickening direction for axis-aligned thick lines: vertical (dx==0) spreads in
  // +x; horizontal (dy==0) spreads in +y (pygame's width>1 perpendicular fill).
  const tx = dx === 0 ? 1 : 0;
  const ty = dy === 0 ? 1 : 0;
  let err = dx - dy;
  let x = x0;
  let y = y0;
  for (;;) {
    for (let t = 0; t < Math.max(1, width); t++) {
      const px = x + tx * t;
      const py = y + ty * t;
      if (px >= 0 && px < buf.w && py >= 0 && py < buf.h) {
        const ai = px * buf.h + py;
        const ri = ai * 3;
        buf.rgb[ri] = rgb[0];
        buf.rgb[ri + 1] = rgb[1];
        buf.rgb[ri + 2] = rgb[2];
        buf.alpha[ai] = 255;
      }
    }
    if (x === x1 && y === y1) break;
    const e2 = 2 * err;
    if (e2 > -dy) {
      err -= dy;
      x += sx;
    }
    if (e2 < dx) {
      err += dx;
      y += sy;
    }
  }
}

/**
 * Render design `idx` with its ORIGIN (the ground/wheel row, dy==0) at (px, py) in
 * buffer coords (sprites.py _draw_strokes_into).  `facing` 1 = right (dx as-is), -1
 * = left (mirror x).  `angle` is render.py convention (0=E, 90=up, 180=W); the
 * barrel is drawn from the design's turret mount at that angle.  `barrelRgb`
 * undefined = derive from the team color; pass an RGB to override.
 */
function drawStrokesIntoBuf(
  buf: PixelBuffer,
  px: number,
  py: number,
  color: RGB,
  idx: number,
  opts: {
    facing?: number;
    angle?: number;
    scale?: number;
    barrelRgb?: RGB | null;
    drawBarrel?: boolean;
  } = {},
): void {
  const facing = opts.facing ?? 1;
  const angle = opts.angle ?? 90;
  const scale = opts.scale ?? 1;
  const drawBarrel = opts.drawBarrel ?? true;
  const di = designIndex(idx);
  const strokes = data.TANK_STROKES[di];
  for (const [dx, dy, c] of strokes) {
    const sx = px + (facing >= 0 ? dx : -dx) * scale;
    const sy = py + dy * scale;
    plotBlock(buf, sx, sy, scale, shadeRgb(color, c));
  }
  if (drawBarrel) {
    // Barrel from the turret mount at the aim angle (FUN_4912_021f geometry).
    // length = per-design word0 (Target 2), not a flat 8.
    const mount = data.TANK_TURRET[di] ?? [0, 0];
    const tx = mount[0];
    const ty = mount[1];
    const blen = barrelLen(di);
    const ox = px + (facing >= 0 ? tx : -tx) * scale;
    const oy = py + ty * scale;
    const rad = (angle * Math.PI) / 180;
    const bx = ox + Math.round(Math.cos(rad) * blen * scale);
    const by = oy - Math.round(Math.sin(rad) * blen * scale);
    const bcol = opts.barrelRgb != null ? opts.barrelRgb : barrelColor(color);
    bresenhamLine(buf, ox, oy, bx, by, Math.max(1, scale), bcol);
  }
}

/** (minx, maxx, miny, maxy) of design `idx`'s strokes (sprites.py _design_bbox). */
function designBbox(idx: number): [number, number, number, number] {
  const s = data.TANK_STROKES[designIndex(idx)];
  let minx = Infinity;
  let maxx = -Infinity;
  let miny = Infinity;
  let maxy = -Infinity;
  for (const p of s) {
    if (p[0] < minx) minx = p[0];
    if (p[0] > maxx) maxx = p[0];
    if (p[1] < miny) miny = p[1];
    if (p[1] > maxy) maxy = p[1];
  }
  return [minx, maxx, miny, maxy];
}

/**
 * Resolve `color` (an RGB triple OR an int palette index, with `pal` supplied) to
 * an RGB, matching draw_tank's head (sprites.py:621-628).
 */
function resolveColor(
  color: RGB | number,
  pal?: _pal.PaletteTable,
): RGB {
  if (typeof color === "number") {
    if (pal !== undefined && pal !== null) {
      const row = pal[Math.max(0, Math.min(255, color))];
      return [row[0] | 0, row[1] | 0, row[2] | 0];
    }
    const v = data.VIS_RGB[Math.abs(color)];
    return v !== undefined ? [v[0], v[1], v[2]] : [200, 200, 200];
  }
  return color;
}

/**
 * Compute the tank-body plots for design `idx` at origin (px,py) WITHOUT a Surface:
 * returns the column-major pixel buffer of width bufW x bufH.  Shared by the test
 * (asserts pixels) and draw_tank/draw_tank_icon_cell (stamp onto a Surface).  This
 * is the single code path, so the test exercises exactly what the Surface methods do.
 */
export function tankBodyPixels(
  bufW: number,
  bufH: number,
  px: number,
  py: number,
  color: RGB,
  idx: number,
  opts: {
    facing?: number;
    angle?: number;
    scale?: number;
    barrelRgb?: RGB | null;
    drawBarrel?: boolean;
  } = {},
): PixelBuffer {
  const buf = blankBuffer(bufW, bufH);
  drawStrokesIntoBuf(buf, px, py, color, idx, opts);
  return buf;
}

/** Stamp every opaque pixel of `buf` onto `surf` via set_at (the compositing path
 *  draw_tank/draw_tank_icon_cell take, equivalent to set_at/fill onto the target). */
/** A built tank-body sprite: the SRCALPHA surface plus the blit offset of its
 *  top-left relative to the stamp origin (the wheel-row center the drawers pass). */
interface TankSprite {
  surf: pygame.Surface;
  ox: number;
  oy: number;
}

// Tank sprites used to be re-decoded and stamped PIXEL BY PIXEL (set_at = a
// clearRect+fillRect pair) into a buffer spanning the WHOLE target surface,
// every frame, per tank/cell -- 53.7% of all CPU self-time on the tank-setup
// screen in the 2026-07-07 device profile. The pixels are a pure function of
// the key below, so build each variant ONCE (tight bbox-sized buffer -> the
// same surfaceFromBuffer path get_sprite uses) and blit thereafter. Blitting an
// SRCALPHA sprite source-over writes exactly the pixels stampBuffer wrote
// (opaque cells replace, transparent cells leave the target untouched).
const _tankSpriteCache = new Map<string, TankSprite>();
const _TANK_SPRITE_CACHE_CAP = 512;

function tankSprite(
  rgb: RGB,
  idx: number,
  opts: { facing: number; angle: number; scale: number; barrelRgb: RGB | null; drawBarrel: boolean },
): TankSprite {
  const key =
    idx +
    "|" +
    rgb.join(",") +
    "|" +
    opts.scale +
    "|" +
    opts.angle +
    "|" +
    opts.facing +
    "|" +
    (opts.barrelRgb === null ? "-" : opts.barrelRgb.join(",")) +
    "|" +
    opts.drawBarrel;
  const hit = _tankSpriteCache.get(key);
  if (hit !== undefined) return hit;
  // Tight extent around the stamp origin: hull strokes (designBbox) plus the
  // barrel, which may point anywhere from the turret mount (facing mirrors x,
  // so the x reach is symmetric). Margins are deliberately generous; the buffer
  // is dozens of pixels on a side either way.
  const di = designIndex(idx);
  const [minx, maxx, miny, maxyv] = designBbox(idx);
  const bl = barrelLen(di);
  const mount = data.TANK_TURRET[di] ?? [0, 0];
  const reach = Math.max(maxx, -minx) + bl + 2;
  const y0 = Math.min(miny, mount[1] - bl) - 2;
  const y1 = maxyv + bl + 2;
  const scale = opts.scale;
  const tw = (2 * reach + 1) * scale;
  const th = (y1 - y0 + 1) * scale;
  const buf = tankBodyPixels(tw, th, reach * scale, -y0 * scale, rgb, idx, {
    facing: opts.facing,
    angle: opts.angle,
    scale,
    barrelRgb: opts.barrelRgb,
    drawBarrel: opts.drawBarrel,
  });
  const sprite: TankSprite = { surf: surfaceFromBuffer(buf), ox: -reach * scale, oy: y0 * scale };
  _tankSpriteCache.set(key, sprite);
  while (_tankSpriteCache.size > _TANK_SPRITE_CACHE_CAP) {
    const oldest = _tankSpriteCache.keys().next().value as string;
    _tankSpriteCache.delete(oldest);
  }
  return sprite;
}

/**
 * Draw the chosen tank body + turret at (x, y).  (sprites.py draw_tank.)
 *
 *   x, y       : screen position of the tank's GROUND-CONTACT point (design origin,
 *                the dy==0 row) -- matches render.py's (t.x, t.y).
 *   icon_index : the tank's APPEARANCE/DESIGN index 0..6.  Out of range clamps to 0.
 *   color      : RGB triple OR an int palette index (with `pal` supplied).
 *   angle      : aim angle, render.py convention (0=E, 90=up, 180=W).
 *   facing     : 1 = right, -1 = left (mirrors x, FUN_49d4_04d9 tank+0x94).
 *
 * The body is composited onto `surf` at absolute coords (the strokes are at
 * x+dx, y+dy), so the pixel buffer spans the surface; only opaque cells are stamped.
 */
export function draw_tank(
  surf: pygame.Surface,
  x: number,
  y: number,
  icon_index: number,
  color: RGB | number,
  angle: number,
  opts: { scale?: number; pal?: unknown; facing?: number } = {},
): void {
  const scale = opts.scale ?? 1;
  const facing = opts.facing ?? 1;
  const rgb = resolveColor(color, asPalette(opts.pal));
  const t = tankSprite(rgb, Math.trunc(icon_index), {
    facing,
    angle,
    scale,
    barrelRgb: null,
    drawBarrel: true,
  });
  surf.blit(t.surf, [x + t.ox, y + t.oy]);
}

/**
 * Paint ONE Tank-Initialization appearance cell with its OWN design.
 * (sprites.py draw_tank_icon_cell.)
 *
 * Renders the recovered design `design_index` (0..6) tinted to `color`, centered in
 * `box` (a pygame.Rect), barrel at rest (straight up).  `triple`/`wheels` are
 * accepted for caller back-compat but ignored: the design's own recovered shape is
 * authoritative (idx6 is a single-turret tank, NOT three barrels).
 */
export function draw_tank_icon_cell(
  surf: pygame.Surface,
  box: pygame.Rect,
  color: RGB,
  opts: {
    design_index?: number;
    grayed?: boolean;
    scale?: number;
    triple?: unknown;
    wheels?: unknown;
  } = {},
): void {
  const designIdx = Math.trunc(opts.design_index ?? 0);
  const scale = opts.scale ?? 2;
  const grayed = opts.grayed ?? false;
  const rgb: RGB = grayed ? [120, 120, 120] : color;
  const barrel: RGB | null = grayed ? [150, 150, 150] : null; // null -> derive
  const [minx, maxx, miny] = designBbox(designIdx);
  // The drawn extent runs from the barrel tip (above the turret mount) down to the
  // wheel row (dy==0).  Center that whole extent in the cell.
  const mount = data.TANK_TURRET[designIndex(designIdx)] ?? [0, 0];
  const ty = mount[1];
  const top = Math.min(miny, ty - barrelLen(designIndex(designIdx))); // highest drawn pixel
  const bottom = maxy(designIdx); // = 0 (wheel row)
  const cx = box.centerx;
  const extentH = (bottom - top) * scale;
  // Python int // 2 floor-div; extentH >= 0 so >> 1 (toward -inf for non-neg) matches.
  const originY = box.centery + Math.floor(extentH / 2) - bottom * scale;
  const t = tankSprite(rgb, designIdx, {
    facing: 1,
    angle: 90,
    scale,
    barrelRgb: barrel,
    drawBarrel: true,
  });
  surf.blit(t.surf, [cx + t.ox, originY + t.oy]);
}

/** maxy of a design's strokes (the wheel row, = 0); split out so draw_tank_icon_cell
 *  reads the same bbox the oracle does. */
function maxy(idx: number): number {
  return designBbox(idx)[3];
}

/** Return a list of tank Surfaces (design `idx`), one per requested color
 *  (sprites.py get_tank_icons).  Used for appearance pickers / previews. */
export function get_tank_icons(opts: {
  colors?: RGB[];
  scale?: number;
  idx?: number;
} = {}): pygame.Surface[] {
  const scale = opts.scale ?? 2;
  const idx = opts.idx ?? 0;
  const colors =
    opts.colors ??
    ([
      [255, 64, 64],
      [64, 128, 255],
      [64, 255, 64],
      [255, 255, 64],
      [255, 128, 0],
      [192, 64, 255],
      [0, 224, 224],
      [255, 128, 192],
      [160, 160, 160],
      [255, 255, 255],
    ] as RGB[]);
  const [minx, maxx, miny, maxyv] = designBbox(idx);
  const padTop = -miny + barrelLen(idx) + 1;
  const w = (maxx - minx + 3) * scale;
  const h = (padTop + 2) * scale;
  const icons: pygame.Surface[] = [];
  for (const col of colors) {
    const px = (-minx + 1) * scale;
    const py = (padTop - 1) * scale; // origin (wheel row) near the bottom
    const buf = tankBodyPixels(w, h, px, py, col, idx, { angle: 90, scale });
    icons.push(surfaceFromBuffer(buf));
  }
  return icons;
}

/** (width, height, set of "x,y") of design `idx`'s strokes in bbox-local coords
 *  (top-left origin).  For tests / non-pygame rendering (sprites.py tank_silhouette). */
export function tank_silhouette(idx = 0): { w: number; h: number; local: Set<string> } {
  const [minx, maxx, miny, maxyv] = designBbox(idx);
  const w = maxx - minx + 1;
  const h = maxyv - miny + 1;
  const local = new Set<string>();
  for (const [x, y] of data.TANK_STROKES[designIndex(idx)]) {
    local.add(`${x - minx},${y - miny}`);
  }
  return { w, h, local };
}

// ==========================================================================
// REAL proportional BITMAP FONT (sprites_data.FONT_GLYPH_BYTES) -- byte-exact.
//
// Glyph data (FUN_5571_0180 / FUN_5589_0684): byte0 = WIDTH (0 = blank); next
// 12*WIDTH bytes = 12 ROWS of `width` bytes, a NONZERO byte = a set pixel.  Cell
// height 12.  Advance is width+1; the `~` (0x7e) color escape consumes no width.
// ==========================================================================

const FONT_ROWS = data.FONT_ROWS; // 12

/** (width, rows) for a character code, or (0, []) if absent (sprites.py _font_decode). */
export function fontDecode(code: number): { width: number; rows: number[][] } {
  const bytes = data.FONT_GLYPH_BYTES[code];
  if (bytes === undefined) return { width: 0, rows: [] };
  const w = bytes[0];
  const rows: number[][] = [];
  let p = 1;
  for (let r = 0; r < FONT_ROWS; r++) {
    rows.push(Array.from(bytes.subarray(p, p + w)));
    p += w;
  }
  return { width: w, rows };
}

/** Pixel width of one glyph (0 if blank/absent).  Advance is width+1. */
export function font_glyph_width(code: number): number {
  const bytes = data.FONT_GLYPH_BYTES[code];
  return bytes !== undefined ? bytes[0] : 0;
}

/** Pixel width of a string (FUN_5589_0b87: sum(width+1); `~` consumes no width). */
export function font_text_width(s: string): number {
  let total = 0;
  for (const ch of s) {
    if (ch === "~") continue;
    total += font_glyph_width(ch.codePointAt(0)!) + 1;
  }
  return total;
}

/** Every character code with a real (width>0) glyph, sorted. */
export function font_codes(): number[] {
  return Object.keys(data.FONT_GLYPH_BYTES)
    .map((k) => Number(k))
    .filter((c) => font_glyph_width(c) > 0)
    .sort((a, b) => a - b);
}

/** Build a per-pixel-alpha pixel buffer for one glyph code (sprites.py
 *  get_font_glyph).  Transparent where clear; `rgb` is the ink color. */
export function fontGlyphPixels(
  code: number,
  rgb: RGB = [235, 235, 245],
  scale = 1,
): PixelBuffer {
  const { width: w, rows } = fontDecode(code);
  const buf = blankBuffer(w * scale, FONT_ROWS * scale);
  for (let ry = 0; ry < FONT_ROWS; ry++) {
    const row = ry < rows.length ? rows[ry] : [];
    for (let rx = 0; rx < w; rx++) {
      if (rx < row.length && row[rx]) {
        plotBlock(buf, rx * scale, ry * scale, scale, rgb);
      }
    }
  }
  return buf;
}

/** A per-pixel-alpha Surface for one glyph code (sprites.py get_font_glyph). */
export function get_font_glyph(
  code: number,
  rgb: RGB = [235, 235, 245],
  scale = 1,
): pygame.Surface {
  return surfaceFromBuffer(fontGlyphPixels(code, rgb, scale));
}

/** Render a string with the authentic bitmap font into one pixel buffer
 *  (sprites.py render_text advance = width + spacing; `~` skipped). */
export function renderTextPixels(
  s: string,
  rgb: RGB = [235, 235, 245],
  scale = 1,
  spacing = 1,
): PixelBuffer {
  const width = Math.max(1, font_text_width(s) * scale);
  const buf = blankBuffer(width, FONT_ROWS * scale);
  let x = 0;
  for (const ch of s) {
    if (ch === "~") continue;
    const code = ch.codePointAt(0)!;
    const w = font_glyph_width(code);
    if (w) {
      const g = fontGlyphPixels(code, rgb, scale);
      // blit g at (x*scale, 0): copy opaque cells into buf.
      for (let gx = 0; gx < g.w; gx++) {
        const dstX = x * scale + gx;
        if (dstX < 0 || dstX >= buf.w) continue;
        for (let gy = 0; gy < g.h; gy++) {
          const sai = gx * g.h + gy;
          if (g.alpha[sai] === 0) continue;
          const dai = dstX * buf.h + gy;
          const dri = dai * 3;
          const sri = sai * 3;
          buf.rgb[dri] = g.rgb[sri];
          buf.rgb[dri + 1] = g.rgb[sri + 1];
          buf.rgb[dri + 2] = g.rgb[sri + 2];
          buf.alpha[dai] = 255;
        }
      }
    }
    x += w + spacing;
  }
  return buf;
}

/** Render a string with the authentic bitmap font into one Surface. */
export function render_text(
  s: string,
  rgb: RGB = [235, 235, 245],
  scale = 1,
  spacing = 1,
): pygame.Surface {
  return surfaceFromBuffer(renderTextPixels(s, rgb, scale, spacing));
}

// ==========================================================================
// REAL mouse CURSOR (default arrow) -- sprites_data.CURSOR_POINTS, byte-exact.
// FUN_54e7_06c0 sets hotspot (0,0) + 28 (dx,dy,color) triplets at 5f38:703a;
// FUN_54e7_0147 plots them.  Only geometry is stored (color is runtime-supplied).
// ==========================================================================

export const CURSOR_HOTSPOT = data.CURSOR_HOTSPOT;
export const CURSOR_POINTS = data.CURSOR_POINTS;

/** Build the default arrow cursor as a pixel buffer + hotspot (sprites.py get_cursor). */
export function cursorPixels(
  rgb: RGB = [255, 255, 255],
  scale = 1,
): { buf: PixelBuffer; hotspot: [number, number] } {
  let minx = Infinity;
  let maxx = -Infinity;
  let miny = Infinity;
  let maxy = -Infinity;
  for (const [dx, dy] of CURSOR_POINTS) {
    if (dx < minx) minx = dx;
    if (dx > maxx) maxx = dx;
    if (dy < miny) miny = dy;
    if (dy > maxy) maxy = dy;
  }
  const w = (maxx - minx + 1) * scale;
  const h = (maxy - miny + 1) * scale;
  const buf = blankBuffer(w, h);
  for (const [dx, dy] of CURSOR_POINTS) {
    plotBlock(buf, (dx - minx) * scale, (dy - miny) * scale, scale, rgb);
  }
  const hotspot: [number, number] = [
    (CURSOR_HOTSPOT[0] - minx) * scale,
    (CURSOR_HOTSPOT[1] - miny) * scale,
  ];
  return { buf, hotspot };
}

/** The default arrow cursor as a Surface + hotspot (sprites.py get_cursor). */
export function get_cursor(
  rgb: RGB = [255, 255, 255],
  scale = 1,
): { surf: pygame.Surface; hotspot: [number, number] } {
  const { buf, hotspot } = cursorPixels(rgb, scale);
  return { surf: surfaceFromBuffer(buf), hotspot };
}

// ==========================================================================
// WINDOW ICON -- decoded byte-exact from SCORCH.ICO (sprites_data.ICON_*).
// 32x32 4-bpp DIB: 16-color palette + bottom-up XOR bitmap (stored TOP-DOWN here)
// + 1-bpp AND transparency mask (1 = transparent).
// ==========================================================================

export const ICON_W = data.ICON_W;
export const ICON_H = data.ICON_H;

/** Build the Scorched Earth window icon as a pixel buffer (sprites.py get_window_icon).
 *  Transparent where the .ICO AND mask is set. */
export function windowIconPixels(scale = 1): PixelBuffer {
  const xor = data.ICON_XOR;
  const andb = data.ICON_AND;
  const w = ICON_W;
  const h = ICON_H;
  const buf = blankBuffer(w * scale, h * scale);
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const bi = y * w + x;
      const byte = xor[bi >> 1];
      const idx = (bi & 1) === 0 ? byte >> 4 : byte & 0x0f;
      const abyte = andb[bi >> 3];
      const transparent = (abyte >> (7 - (bi & 7))) & 1;
      if (transparent) continue;
      const p = data.ICON_PALETTE[idx];
      plotBlock(buf, x * scale, y * scale, scale, [p[0], p[1], p[2]]);
    }
  }
  return buf;
}

/** The Scorched Earth window icon as a Surface (sprites.py get_window_icon). */
export function get_window_icon(scale = 1): pygame.Surface {
  return surfaceFromBuffer(windowIconPixels(scale));
}

// ==========================================================================
// TITLE-SCREEN MOUNTAIN -- the digitized grayscale granite photo (.MTN) decoded
// byte-exact via src/mtn.ts (sprites.py load_title_mountain).
//
// The browser cannot read files off disk; the bytes are fetched ahead of time
// (src/assets.ts).  load_title_mountain takes an INJECTED byte source so the test
// can feed real shipped .MTN bytes and the integrator can feed the fetched bytes.
// ==========================================================================

export const TITLE_MTN_DEFAULT = data.TITLE_MTN_DEFAULT;
export const TITLE_MTN_WHITELIST = data.TITLE_MTN_WHITELIST;

/** Injectable .MTN byte source: name -> raw bytes, or null if unavailable.  The
 *  integrator wires this to the fetched-asset cache; the Python reads files off
 *  disk (sprites._data_dir).  Until set, load_title_mountain returns null. */
export type MtnByteSource = (name: string) => Uint8Array | null;

let _mtnByteSource: MtnByteSource | null = null;

/** Integrator hook: supply the .MTN byte source (the fetched-asset reader). */
export function setMtnByteSource(src: MtnByteSource | null): void {
  _mtnByteSource = src;
}

/** Resolve a title-mountain name against the whitelist (find_mtn_file's contract),
 *  returning the upper-cased name or null if off-list (sprites.py title_mountain_path). */
export function titleMountainName(name?: string | null): string | null {
  const fname = name || TITLE_MTN_DEFAULT;
  return TITLE_MTN_WHITELIST.includes(fname.toUpperCase()) ? fname.toUpperCase() : null;
}

/**
 * Decode a title .MTN into an RGBA pixel buffer (ground only; sky alpha 0) from the
 * injected byte source.  Mirrors sprites.py load_title_mountain: GROUND pixels in
 * the file's own (digitized grayscale) palette at full alpha, the unstored SKY left
 * fully transparent.  Returns null when the name is off-whitelist or the bytes are
 * unavailable.  `bytesOverride` feeds bytes directly (the test path).
 */
export function loadTitleMountainPixels(
  name?: string | null,
  bytesOverride?: Uint8Array,
): PixelBuffer | null {
  const fname = titleMountainName(name);
  if (fname === null) return null;
  let bytes: Uint8Array | null = bytesOverride ?? null;
  if (bytes === null) {
    bytes = _mtnByteSource ? _mtnByteSource(fname) : null;
  }
  if (bytes === null) return null;
  const hdr = mtnParseHeader(bytes, fname);
  const palette: MtnRgb[] = hdr.palette;
  const grid = mtnDecode(bytes, fname); // row-major data[y*w+x], -1 = sky
  const w = grid.width;
  const h = grid.height;
  const buf = blankBuffer(w, h);
  // Mirror the oracle's numpy build EXACTLY (sprites.py:1177-1189):
  //   rgb   = palette[where(sky, 0, grid)]   -> RGB written for EVERY cell; sky
  //           cells take palette[0] (the file's white sky slot), NOT left at 0.
  //   alpha = where(sky, 0, 255)             -> 0 for sky, 255 for ground.
  // array3d readback ignores alpha, so the dumped sky RGB is palette[0]; the TS
  // buffer must match (write palette[0] RGB at sky cells, alpha 0).  Plot at scale
  // 1 directly into the column-major buffer (rgb[(x*h+y)*3], alpha[x*h+y]).
  const sky = palette[0];
  for (let y = 0; y < h; y++) {
    for (let x = 0; x < w; x++) {
      const v = grid.data[y * w + x];
      const isSky = v < 0;
      const p = isSky ? sky : palette[v];
      const ai = x * h + y;
      const ri = ai * 3;
      buf.rgb[ri] = p[0];
      buf.rgb[ri + 1] = p[1];
      buf.rgb[ri + 2] = p[2];
      buf.alpha[ai] = isSky ? 0 : 255;
    }
  }
  return buf;
}

/**
 * Decode a title .MTN into an RGBA pygame Surface (ground only; sky alpha 0).
 * (sprites.py load_title_mountain; SpritesProvider.load_title_mountain.)
 * Returns null when unavailable.  `bytesOverride` lets a caller pass bytes directly.
 */
export function load_title_mountain(
  name?: string | null,
  bytesOverride?: Uint8Array,
): pygame.Surface | null {
  const buf = loadTitleMountainPixels(name, bytesOverride);
  if (buf === null) return null;
  return surfaceFromBuffer(buf);
}
